export const demoAdvertisementsData = [
  {
    _id: 1,
    title: "UI/UX Designer",
    organizationName: "Bootcamp",
    serviceType: "Training Program",
    focusArea: "Cybersecurity",
    mode: "Online",
    location: "2464 Royal Ln. Mesa, New Jersey 45463",
    pricingOption: "Placement Fee",
    startDate: "01 Jan 2020",
    endDate: "01 Jan 2020",
    contact: "company@gmail.com",
    adType: "Weekly",
    paymentStatus: "Complete",
    status: "Approved",
  },
  {
    _id: 2,
    title: "Frontend Developer Workshop",
    organizationName: "TechNova Solutions",
    serviceType: "Bootcamp",
    focusArea: "Web Development",
    mode: "Online",
    location: "500 Market St, San Francisco, CA 94105",
    pricingOption: "Subscription",
    startDate: "05 Sep 2025",
    endDate: "12 Sep 2025",
    contact: "info@technova.com",
    adType: "Weekly",
    paymentStatus: "Pending",
    status: "Rejected",
  },
  {
    _id: 3,
    title: "Financial Analyst Training",
    organizationName: "FinCore Capital",
    serviceType: "Workshop",
    focusArea: "Finance & Investment",
    mode: "Offline",
    location: "91 5th Ave, New York, NY 10003",
    pricingOption: "Course Fee",
    startDate: "10 Sep 2025",
    endDate: "16 Sep 2025",
    contact: "training@fincore.com",
    adType: "Weekly",
    paymentStatus: "Complete",
    status: "Approved",
  },
  {
    _id: 4,
    title: "Healthcare Assistant Program",
    organizationName: "Medico Health Ltd",
    serviceType: "Training Program",
    focusArea: "Healthcare",
    mode: "Hybrid",
    location: "18 George St, Sydney, Australia",
    pricingOption: "Placement Fee",
    startDate: "01 Jul 2025",
    endDate: "30 Sep 2025",
    contact: "recruit@medicohealth.com",
    adType: "Quarterly",
    paymentStatus: "Overdue",
    status: "Approved",
  },
  {
    _id: 5,
    title: "Project Management Course",
    organizationName: "UrbanBuild Construction",
    serviceType: "Certification Program",
    focusArea: "Construction Management",
    mode: "Online",
    location: "221 Baker St, London, UK",
    pricingOption: "Subscription",
    startDate: "15 Sep 2025",
    endDate: "21 Sep 2025",
    contact: "jobs@urbanbuild.com",
    adType: "Weekly",
    paymentStatus: "Complete",
    status: "Approved",
  },
  {
    _id: 6,
    title: "Hospitality Career Essentials",
    organizationName: "TasteHub Restaurants",
    serviceType: "Workshop",
    focusArea: "Hospitality",
    mode: "Offline",
    location: "22 Rue Lafayette, Paris, France",
    pricingOption: "Registration Fee",
    startDate: "20 Sep 2025",
    endDate: "20 Oct 2025",
    contact: "jobs@tastehub.com",
    adType: "Monthly",
    paymentStatus: "Pending",
    status: "Rejected",
  },
  {
    _id: 7,
    title: "Renewable Energy Engineering",
    organizationName: "EcoFuel Energy",
    serviceType: "Bootcamp",
    focusArea: "Energy",
    mode: "Online",
    location: "88 King St, Vancouver, Canada",
    pricingOption: "Placement Fee",
    startDate: "25 Sep 2025",
    endDate: "01 Oct 2025",
    contact: "careers@ecofuelenergy.com",
    adType: "Weekly",
    paymentStatus: "Complete",
    status: "Approved",
  },
  {
    _id: 8,
    title: "AI & Data Science Bootcamp",
    organizationName: "AquaPure Technologies",
    serviceType: "Training Program",
    focusArea: "Artificial Intelligence",
    mode: "Online",
    location: "Königstraße 30, Stuttgart, Germany",
    pricingOption: "Course Fee",
    startDate: "01 Oct 2025",
    endDate: "01 Nov 2025",
    contact: "work@aquapuretech.io",
    adType: "Monthly",
    paymentStatus: "Processing",
    status: "Approved",
  },
  {
    _id: 9,
    title: "Supply Chain Management Course",
    organizationName: "BlueWave Logistics",
    serviceType: "Workshop",
    focusArea: "Logistics & Transportation",
    mode: "Offline",
    location: "302 Lakeview Dr, Chicago, IL 60610",
    pricingOption: "Subscription",
    startDate: "03 Oct 2025",
    endDate: "09 Oct 2025",
    contact: "careers@bluewave.io",
    adType: "Weekly",
    paymentStatus: "Complete",
    status: "Approved",
  },
  {
    _id: 10,
    title: "AgriTech Innovation Training",
    organizationName: "GreenLeaf Organics",
    serviceType: "Training Program",
    focusArea: "Agriculture Technology",
    mode: "Hybrid",
    location: "Hilltop Rd, Manchester, UK",
    pricingOption: "Placement Fee",
    startDate: "05 Oct 2025",
    endDate: "05 Nov 2025",
    contact: "jobs@greenleaf.co",
    adType: "Monthly",
    paymentStatus: "Pending",
    status: "Rejected",
  },
];
