export const demoJobPostsData = [
  {
    SL: 1,
    companyName: "TechNova Solutions",
    email: "hr@technova.com",
    contact: "+1 202-555-0178",
    category: "Information Technology",
    endDate: "2025-11-15",
    status: "Open",
  },
  {
    SL: 2,
    companyName: "GreenLeaf Organics",
    email: "jobs@greenleaf.co",
    contact: "+44 7911 123456",
    category: "Agriculture",
    endDate: "2025-10-30",
    status: "Pending",
  },
  {
    SL: 3,
    companyName: "BlueWave Logistics",
    email: "careers@bluewave.io",
    contact: "+1 312-555-2098",
    category: "Transportation",
    endDate: "2025-12-05",
    status: "Open",
  },
  {
    SL: 4,
    companyName: "Medico Health Ltd",
    email: "recruit@medicohealth.com",
    contact: "+61 412 345 678",
    category: "Healthcare",
    endDate: "2025-11-02",
    status: "Closed",
  },
  {
    SL: 5,
    companyName: "UrbanBuild Construction",
    email: "jobs@urbanbuild.com",
    contact: "+1 415-555-9922",
    category: "Construction",
    endDate: "2025-12-10",
    status: "Open",
  },
  {
    SL: 6,
    companyName: "BrightPath Education",
    email: "hiring@brightpath.edu",
    contact: "+91 99876 54321",
    category: "Education",
    endDate: "2025-11-20",
    status: "Pending",
  },
  {
    SL: 7,
    companyName: "EcoFuel Energy",
    email: "careers@ecofuelenergy.com",
    contact: "+1 604-555-2201",
    category: "Energy",
    endDate: "2025-10-25",
    status: "Closed",
  },
  {
    SL: 8,
    companyName: "AquaPure Technologies",
    email: "work@aquapuretech.io",
    contact: "+49 170 1234567",
    category: "Environmental Services",
    endDate: "2025-11-05",
    status: "Open",
  },
  {
    SL: 9,
    companyName: "FinCore Capital",
    email: "recruitment@fincore.com",
    contact: "+1 917-555-1144",
    category: "Finance",
    endDate: "2025-12-01",
    status: "Open",
  },
  {
    SL: 10,
    companyName: "TasteHub Restaurants",
    email: "jobs@tastehub.com",
    contact: "+33 6 12 34 56 78",
    category: "Hospitality",
    endDate: "2025-11-28",
    status: "Pending",
  },
];
