export const demoUsersData = [
  {
    _id: "01",
    firstName: "Ahmed",
    lastName: "Al-Farsi",
    userId: "123456",
    gender: "Male",
    email: "ahmed.alfarsi@example.com",
    phone: "1234567890",
    role: "Provider",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
    birthday: "1990-05-15",
    bio: "Passionate about selling second-hand electronics and gadgets.",
    location: "Dubai, UAE",
    status: "Pending",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "02",
    firstName: "Fatima",
    lastName: "Al-Mansouri",
    userId: "123456",
    gender: "Female",
    email: "fatima.almansouri@example.com",
    phone: "1234567890",
    role: "Customer",
    category: "",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
    birthday: "1985-08-20",
    bio: "Loves finding unique second-hand clothing.",
    location: "Abu Dhabi, UAE",
    status: "Approved",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "03",
    firstName: "Mohammed",
    lastName: "Al-Nuaimi",
    userId: "123456",
    gender: "Male",
    email: "mohammed.alnuaimi@example.com",
    phone: "1234567890",
    role: "Provider",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/men/3.jpg",
    birthday: "1992-11-10",
    bio: "Specializes in selling pre-loved footwear.",
    location: "Sharjah, UAE",
    status: "Pending",
    isVacation: true,
    isVerified: true,
    isBlocked: true,
    isDeleted: false,
  },
  {
    _id: "04",
    firstName: "Aisha",
    lastName: "Al-Zaabi",
    userId: "123456",
    gender: "Female",
    email: "aisha.alzaabi@example.com",
    phone: "1234567890",
    role: "Provider",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/women/4.jpg",
    birthday: "1995-03-25",
    bio: "Enjoys shopping for vintage accessories.",
    location: "Ajman, UAE",
    status: "Rejected",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "05",
    firstName: "Omar",
    lastName: "Al-Shehhi",
    userId: "123456",
    gender: "Male",
    email: "omar.alshehhi@example.com",
    phone: "1234567890",
    role: "Customer",
    category: "",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
    birthday: "1988-07-12",
    bio: "Oversees platform operations and user management.",
    location: "Fujairah, UAE",
    status: "Pending",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "06",
    firstName: "Hana",
    lastName: "Al-Dhaheri",
    userId: "123456",
    gender: "Female",
    email: "hana.aldhaheri@example.com",
    phone: "1234567890",
    role: "Provider",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/women/6.jpg",
    birthday: "1993-09-18",
    bio: "Sells second-hand handbags and jewelry.",
    location: "Ras Al Khaimah, UAE",
    status: "Pending",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "07",
    firstName: "Yousef",
    lastName: "Al-Mazrouei",
    userId: "123456",
    gender: "Male",
    email: "yousef.almazrouei@example.com",
    phone: "1234567890",
    role: "Customer",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
    birthday: "1997-01-05",
    bio: "Looking for affordable sportswear and gadgets.",
    location: "Umm Al Quwain, UAE",
    status: "Pending",
    isVacation: false,
    isVerified: true,
    isBlocked: true,
    isDeleted: false,
  },
  {
    _id: "08",
    firstName: "Layla",
    lastName: "Al-Ketbi",
    userId: "123456",
    gender: "Female",
    email: "layla.alketbi@example.com",
    phone: "1234567890",
    role: "Provider",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/women/8.jpg",
    birthday: "1991-06-30",
    bio: "Specializes in selling pre-loved clothing.",
    location: "Dubai, UAE",
    status: "Pending",
    isVacation: true,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "09",
    firstName: "Khalid",
    lastName: "Al-Rashidi",
    userId: "123456",
    gender: "Male",
    email: "khalid.alrashidi@example.com",
    phone: "1234567890",
    role: "Provider",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/men/9.jpg",
    birthday: "1983-04-22",
    bio: "Interested in vintage watches and accessories.",
    location: "Abu Dhabi, UAE",
    status: "Pending",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "10",
    firstName: "Mariam",
    lastName: "Al-Hosani",
    userId: "123456",
    gender: "Female",
    email: "mariam.alhosani@example.com",
    phone: "1234567890",
    role: "Provider",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/women/10.jpg",
    birthday: "1996-12-14",
    bio: "Sells second-hand home decor and furniture.",
    location: "Sharjah, UAE",
    status: "Pending",
    isVacation: false,
    isVerified: true,
    isBlocked: true,
    isDeleted: false,
  },
  {
    _id: "11",
    firstName: "Salim",
    lastName: "Al-Nahyan",
    userId: "123456",
    gender: "Male",
    email: "salim.alnahyan@example.com",
    phone: "1234567890",
    role: "Admin",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/men/11.jpg",
    birthday: "1987-02-17",
    bio: "Ensures smooth platform functionality and security.",
    location: "Ajman, UAE",
    status: "Pending",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "12",
    firstName: "Noor",
    lastName: "Al-Harbi",
    userId: "123456",
    gender: "Female",
    email: "noor.alharbi@example.com",
    phone: "1234567890",
    role: "Provider",
    category: "Cleaner",
    license: "123456",
    photo: "https://randomuser.me/api/portraits/women/12.jpg",
    birthday: "1994-10-08",
    bio: "Loves finding unique second-hand books and collectibles.",
    location: "Fujairah, UAE",
    status: "Pending",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
];
